[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "slab"
no-cv-ss = true
export-glyph-names = false
no-ligation = true

  [buildPlans.iosevka-custom.variants]
  inherits = "ss18"

    [buildPlans.iosevka-custom.variants.design]
    capital-q = "crossing"
    e = "rounded"
    f = "serifed"
    g = "double-storey"
    l = "serifed-flat-tailed"
    q = "straight-serifed"
    r = "serifed"
    w = "straight-flat-top-serifless"
    zero = "slashed"
    five = "upright-flat"
    eight = "two-circles"
    nine = "straight-bar"
    asterisk = "hex-low"
    brace = "curly-flat-boundary"
    at = "fourfold"

[buildPlans.iosevka-custom.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-custom.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-custom.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-custom.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-custom.slopes.oblique]
angle = 9.4
shape = "oblique"
menu = "oblique"
css = "oblique"
