#!/usr/bin/env bash
set -ex

OUTPUT="private-build-plans.toml"

cat sans.toml > "$OUTPUT"

echo >> "$OUTPUT"
echo >> "$OUTPUT"

cat slab.toml \
	| sed -E 's/IosevkaCustom/IosevkaCustomSlab/' \
	| sed -E 's/family = "[^"]+"/family = "Iosevka Custom Slab"/' \
	>> "$OUTPUT"

rm -rf ./dist
mkdir -p ./.build ./font-glyphs ./font-otl ./dist
docker pull mikewhy/docker-iosevka-custom-build:latest
docker run --rm -t \
  --user "$UID" \
  --volume "$PWD/.build:/app/.build" \
  --volume "$PWD/font-glyphs:/app/packages/font-glyphs" \
  --volume "$PWD/font-otl:/app/packages/font-otl" \
  --volume "$PWD/dist:/app/dist" \
  --volume "$PWD/private-build-plans.toml:/app/private-build-plans.toml" \
  mikewhy/docker-iosevka-custom-build:latest \
  npm run build ttf::IosevkaCustom ttf::IosevkaCustomSlab

find dist -type d -name ttf-unhinted -exec rm -rf {} \;
