#!/usr/bin/env bash
set -ex

RELEASE_TAG="release-$(date "+%F-%H-%M")"

rm -f mikew-iosevka-custom.zip
pushd dist/nerd || exit 1
  zip -r ../../mikew-iosevka-custom.zip *
popd

gh release create "$RELEASE_TAG" --generate-notes --target "$GITHUB_SHA"
gh release upload "$RELEASE_TAG" mikew-iosevka-custom.zip
