name: CI

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: ./script/build
      - run: ./script/deploy
        if: endsWith(github.ref, '/main')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
